<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CPC.Application\CPC.Application.csproj" />
    <ProjectReference Include="..\CPC.Domain\CPC.Domain.csproj" />
    <ProjectReference Include="..\CPC.Infrastructure.DataPersistent\CPC.Infrastructure.DataPersistent.csproj" />
  </ItemGroup>

</Project>
