import type { Metadata } from "next"
import { roboto, montserrat } from "@/utils/fonts"
import "./globals.css"
import Navbar from "@/components/ui/Navbar"

export const metadata: Metadata = {
    title: "Simulación de pacientes",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto.variable} ${montserrat.variable} antialiased`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    )
}
